services:
  - type: web
    name: agent-kadi
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
        description: Votre clé API DeepSeek
      - key: CONTACT_PHONE
        value: 0140505518
      - key: MY_PERSONAL_NUMBER
        value: 2250710076550
      - key: CATALOG_LINK
        value: https://wa.me/c/122990784208917
      - key: PORT
        value: 3000